layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - Mideas
     - robloxGameLogs
     - spellChecker.js
     - hackBlox
     - OpenStreetBlox

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: MoaufmKlo
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: channel/UCGgetCMrVdbTFtqe1LeTE9g

topics:
  - name: node.js
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png

  - name: discord.js
    web_url: https://github.com/topics/discordjs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/discord/discord.png

  - name: Roblox
    web_url: https://github.com/topics/roblox
    image_url: https://raw.githubusercontent.com/MoaufmKlo/moaufmklo.com/master/roblox.png
